name: PR Gate 
on:
  pull_request:
    branches:
      - master 
jobs:
  pr-merge-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      # With running the tests like this, there's a danger that someone could add a 
      # nested module and forget to update this list.  However, this approach is very
      # simple, and at a certain point you have to trust the maintainers of a service
      # to catch this kind of stuff during PR review.
      - run: |
          go test
          cd api && go test 